  <template>
  <div class="text-center">
   
    <v-chip
      x-small
      class="ma-2"
      color="white"
      text-color="#015FAF"
    >
      CORPORATE
    </v-chip>
      <v-chip
      x-small
      class="ma-2"
      color="white"
      text-color="#015FAF"
    >
      CORPORATE
    </v-chip>
    <v-chip
      x-small
      class="ma-2"
      color="white"
      text-color="#015FAF"
    >
      CAREER
    </v-chip>
    <v-chip
      x-small
      class="ma-2"
      color="white"
      text-color="#015FAF"
    >
      LOGIN
    </v-chip>
  </div>
</template>